### ISSUE TITLE
FastFail not working

### ISSUE THREAD

**Issue by Insightonic0001** [PulseLane/FastFail#1]
Ever since the recent Beat Saber (multiplayer) update, FastFail hasn't been working. I tried installing it through ModAssistant and also tried installing it myself downloading the file here. I'm not sure if I'm doing something wrong, but failing songs makes me wait the same ~ 5 seconds and it's really annoying.

**Comment by PulseLane** [comment]
Can you share logs and also confirm that both options in the settings are enabled?

**Comment by Insightonic0001** [comment]
Hi,

False alarm. I just uninstalled all mods + Beat Saber and reinstalled everything and it's working. Thanks for this great mod! Literally the one thing that makes this game playable for me.
